# Generated by Django 2.2.17 on 2020-12-23 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formtemplate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='usercenter.Department', verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
